site_name: capo-tools documentation
site_description: Documentation for capo-tools
repo_url: https://github.com/capo-urjc/python-tools
repo_name: capo-urjc/python-tools

theme:
  name: material
  icon:
      repo: fontawesome/brands/github-alt
  features:
    - navigation.tabs

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true

plugins:
  - search
  - gen-files:
      scripts:
        - "scripts/gen_ref_nav.py"
  - literate-nav:
      nav_file: SUMMARY.md-
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          import:
            - https://docs.python.org/3/objects.inv
            - https://mkdocstrings.github.io/objects.inv
            - https://mkdocstrings.github.io/griffe/objects.inv
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            filters: [ "!^_" ]
            heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            preload_modules: [ mkdocstrings ]
            separate_signature: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            unwrap_annotated: true
  - git-committers:
      enabled: !ENV [DEPLOY, false]
      repository: capo-urjc/python-tools

nav:
  - Home: index.md
  - API reference:
    - capo-tools: reference/
  - Acciones explicadas: acciones_explicadas.md
  - Manual de usuario: manual_de_usuario.md