site_name: "Documentación del Proyecto"
docs_dir: .
nav:
  - Home: README.md  # Usamos README.md como único archivo de navegación

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
        paths: ["src"]
        selection:
          docstring_style: google

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite
