name: Upload Python Package

on:
  workflow_dispatch

permissions:
    contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4

    - name: Install dependencies
      run: pdm install

    - name: Build docs
      run: pdm run duty docs