# This workflow will generate and publish documentation in docs/api.md

name: Generate and Publish Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install PDM
      run: |
        python -m pip install --upgrade pip
        python -m pip install pdm

    - name: Install dependencies
      run: pdm install -G dev

    - name: Build and Deploy Documentation
      run: pdm run mkdocs gh-deploy --force