# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4
    
    # You are now able to use PDM in your workflow
    - name: Install dependencies
      run: pdm install

    # Compiling the Python package
    # Generate the distribution files: `sdist` (source Distribution) and `wheel` (binary)
    - name: Build package
      run: pdm build

    # Ensure Twine is installed
    - name: Install Twine
      run: python -m pip install --upgrade twine

    # Publish package to TestPyPI using Twine
    # Here we use my credentials
    - name: Publish package to TestPyPI
      env:
        TWINE_USERNAME: david.garcia  # TestPyPI user
        TWINE_PASSWORD: hrfvbwriguwrh12380  # TestPyPI password
      run: |
        twine upload --repository-url https://test.pypi.org/legacy/ --verbose dist/* --skip-existing # Upload the files to TestPyPI