# This workflow will generate and publish documentation in docs

name: Generate and Publish Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4

    - name: Install dependencies
      run: |
        pdm install -G dev

    - name: Build MkDocs documentation
      run: mkdocs build --site-dir docs

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add docs/
        git commit -m "Update generated documentation"
        git push
